spring.application.name=orchestrator
server:
  port: 8080

spring:
  application:
    name: neuro-symbolic-orchestrator

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

ai-engines:
  url: http://127.0.0.1:8000/evaluate